name: Mise à jour automatique des livres (DÉSACTIVÉ - Lancer localement)

on:
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le repo
        uses: actions/checkout@v4.2.0

      - name: Installer Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Lancer le scraper
        run: python scrape_lbf.py

      - name: Vérifier les changements
        run: git status

      - name: Commit & Push des mises à jour
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || (git commit -m "Mise à jour automatique de rare_books.txt" && git push)
        continue-on-error: true
